name: Push images on dev branch update

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    name: OPEX web app build
    env:
      TAG: dev
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Build Docker images
        env:
          GENERATE_SOURCEMAP: '' 
        run: docker-compose -f docker-compose.build.yml build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images to GitHub Container Registry
        run: docker-compose -f docker-compose.build.yml push
