name: Build on pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: OPEX web app build
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Build Docker images
        env:
          TAG: latest
          GENERATE_SOURCEMAP: false
        run: docker-compose -f docker-compose.build.yml build
